// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Recoil from "recoil";
import * as Recoil$1 from "./recoil";

var RecoilRoot = {};

var atom = Recoil$1.atom;

var doSomething = function useSomeHook(snapshot) {
  console.log("DebugObserver :: The following atoms were modified:");
  for (const node of snapshot.getNodes_UNSTABLE({ isModified: true })) {
    console.debug("DebugObserver :: ", node.key, snapshot.getLoadable(node));
  }
};

function useMake(param) {
  var snapshot = Recoil.useRecoilSnapshot();
  React.useEffect(
    function () {
      doSomething(snapshot);
    },
    [snapshot],
  );
  return null;
}

var DebugObserver = {
  doSomething: doSomething,
  useMake: useMake,
};

export { RecoilRoot, atom, DebugObserver };
/* atom Not a pure module */
