// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as ThemeProvider from "../context/ThemeProvider.bs.js";

function Shimmer(props) {
  var shimmerType = props.shimmerType;
  var styleClass = props.styleClass;
  var styleClass$1 = styleClass !== undefined ? styleClass : "w-96 h-96";
  var shimmerType$1 = shimmerType !== undefined ? shimmerType : /* Small */ 0;
  var theme = ThemeProvider.useTheme(undefined);
  var shimmerClass = shimmerType$1 ? "animate-shimmer-fast" : "animate-shimmer";
  var background = theme
    ? "linear-gradient(94.97deg, rgba(35, 36, 36, 0) 25.3%, #2c2d2d 50.62%, rgba(35, 36, 36, 0) 74.27%)"
    : "linear-gradient(94.97deg, rgba(241, 242, 244, 0) 25.3%, #ebedf0 50.62%, rgba(241, 242, 244, 0) 74.27%)";
  return React.createElement("div", {
    className:
      "" +
      shimmerClass +
      "  border border-solid border-[#ccd2e259] dark:border-[#2e2f3980] dark:bg-black bg-white " +
      styleClass$1 +
      "",
    style: {
      background: background,
    },
  });
}

var make = Shimmer;

export { make };
/* react Not a pure module */
