// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Js_exn from "rescript/lib/es6/js_exn.js";
import * as Js_vector from "rescript/lib/es6/js_vector.js";
import * as Caml_array from "rescript/lib/es6/caml_array.js";
import * as LogicUtils from "../../utils/LogicUtils.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as Caml_splice_call from "rescript/lib/es6/caml_splice_call.js";
import * as JsonFlattenUtils from "../../utils/JsonFlattenUtils.bs.js";
import * as Caml_js_exceptions from "rescript/lib/es6/caml_js_exceptions.js";
import * as SuggestedActionHelper from "./ConnectorUIUtils/SuggestedActionHelper.bs.js";

var stepsArr = [
  /* IntegFields */ 0, /* PaymentMethods */ 1, /* SummaryAndTest */ 2,
];

var payoutStepsArr = [
  /* IntegFields */ 0, /* PaymentMethods */ 1, /* SummaryAndTest */ 2,
];

function getStepName(step) {
  switch (step) {
    case /* IntegFields */ 0:
      return "Credentials";
    case /* PaymentMethods */ 1:
      return "Payment Methods";
    case /* SummaryAndTest */ 2:
      return "Summary";
    case /* Preview */ 3:
      return "Preview";
    case /* AutomaticFlow */ 4:
      return "AutomaticFlow";
  }
}

var payoutConnectorList = [
  {
    TAG: /* Processors */ 0,
    _0: /* ADYEN */ 0,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* WISE */ 47,
  },
];

var threedsAuthenticatorList = [
  {
    TAG: /* ThreeDsAuthenticator */ 1,
    _0: /* THREEDSECUREIO */ 0,
  },
  {
    TAG: /* ThreeDsAuthenticator */ 1,
    _0: /* NETCETERA */ 1,
  },
];

var connectorList = [
  {
    TAG: /* Processors */ 0,
    _0: /* STRIPE */ 6,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PAYPAL */ 26,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* ACI */ 13,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* ADYEN */ 0,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* AIRWALLEX */ 10,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* AUTHORIZEDOTNET */ 5,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BANKOFAMERICA */ 3,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BAMBORA */ 22,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BILLWERK */ 4,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BITPAY */ 36,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BLUESNAP */ 9,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BRAINTREE */ 2,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CASHTOCODE */ 38,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CHECKOUT */ 1,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* COINBASE */ 27,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CRYPTOPAY */ 37,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CYBERSOURCE */ 12,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* DLOCAL */ 20,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* FISERV */ 15,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* FORTE */ 33,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* GLOBALPAY */ 8,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* GLOBEPAY */ 40,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* GOCARDLESS */ 48,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* HELCIM */ 51,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* IATAPAY */ 35,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* KLARNA */ 7,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* MOLLIE */ 23,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* MULTISAFEPAY */ 21,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* NEXINETS */ 34,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* NMI */ 32,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* NOON */ 43,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* NUVEI */ 19,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* OPENNODE */ 28,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PAYME */ 39,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PAYU */ 18,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* POWERTRANZ */ 41,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PROPHETPAY */ 50,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* RAPYD */ 17,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* SHIFT4 */ 16,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* STAX */ 46,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* TRUSTPAY */ 24,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* TSYS */ 42,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* VOLT */ 49,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* WORLDLINE */ 14,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* WORLDPAY */ 11,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* ZEN */ 25,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* ZSL */ 53,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PLACETOPAY */ 52,
  },
];

var connectorListForLive = [
  {
    TAG: /* Processors */ 0,
    _0: /* STRIPE */ 6,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* ADYEN */ 0,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* AUTHORIZEDOTNET */ 5,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PAYPAL */ 26,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BANKOFAMERICA */ 3,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BLUESNAP */ 9,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* BRAINTREE */ 2,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CHECKOUT */ 1,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CRYPTOPAY */ 37,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CASHTOCODE */ 38,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* CYBERSOURCE */ 12,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* IATAPAY */ 35,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* NMI */ 32,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* PAYME */ 39,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* TRUSTPAY */ 24,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* VOLT */ 49,
  },
  {
    TAG: /* Processors */ 0,
    _0: /* ZEN */ 25,
  },
];

var connectorListWithAutomaticFlow = [/* PAYPAL */ 26];

function getPaymentMethodFromString(paymentMethod) {
  var match = paymentMethod.toLowerCase();
  switch (match) {
    case "bank_debit":
      return /* BankDebit */ 6;
    case "bank_redirect":
      return /* BankRedirect */ 3;
    case "bank_transfer":
      return /* BankTransfer */ 4;
    case "crypto":
      return /* Crypto */ 5;
    case "card":
    case "credit":
    case "debit":
      return /* Card */ 0;
    case "paylater":
      return /* PayLater */ 1;
    case "wallet":
      return /* Wallet */ 2;
    default:
      return /* UnknownPaymentMethod */ {
        _0: paymentMethod,
      };
  }
}

function getPaymentMethodTypeFromString(paymentMethodType) {
  var match = paymentMethodType.toLowerCase();
  switch (match) {
    case "apple_pay":
      return /* ApplePay */ 3;
    case "credit":
      return /* Credit */ 0;
    case "debit":
      return /* Debit */ 1;
    case "google_pay":
      return /* GooglePay */ 2;
    default:
      return /* UnknownPaymentMethodType */ {
        _0: paymentMethodType,
      };
  }
}

function dummyConnectorList(isTestProcessorsEnabled) {
  if (isTestProcessorsEnabled) {
    return [
      {
        TAG: /* Processors */ 0,
        _0: /* STRIPE_TEST */ 44,
      },
      {
        TAG: /* Processors */ 0,
        _0: /* PAYPAL_TEST */ 45,
      },
      {
        TAG: /* Processors */ 0,
        _0: /* FAUXPAY */ 30,
      },
      {
        TAG: /* Processors */ 0,
        _0: /* PRETENDPAY */ 31,
      },
    ];
  } else {
    return [];
  }
}

function checkIsDummyConnector(connectorName, isTestProcessorsEnabled) {
  return dummyConnectorList(isTestProcessorsEnabled).includes(connectorName);
}

var stripeInfo_validate = [
  {
    name: "connector_account_details.api_key",
    liveValidationRegex: "^sk_live_(.+)$",
    testValidationRegex: "^sk_test_(.+)$",
    liveExpectedFormat: "Secret key should have the prefix sk_live_",
    testExpectedFormat: "Secret key should have the prefix sk_test_",
  },
];

var stripeInfo = {
  description:
    "Versatile processor supporting credit cards, digital wallets, and bank transfers.",
  validate: stripeInfo_validate,
};

var goCardLessInfo = {
  description:
    "Simplify payment collection with a single, hassle-free integration across 30+ countries for Direct Debit payments.",
};

var adyenInfo = {
  description:
    "Global processor accepting major credit cards, e-wallets, and local payment methods.",
};

var checkoutInfo_validate = [
  {
    name: "connector_account_details.api_key",
    liveValidationRegex: "^pk(?!_sbox).*",
    testValidationRegex: "^pk(_sbox)?_(.+)$",
    liveExpectedFormat:
      "API public key should begin with pk_ and not begin with pk_sbox_",
    testExpectedFormat: "API public key should begin with pk_",
  },
  {
    name: "connector_account_details.api_secret",
    liveValidationRegex: "^sk(?!_sbox).*",
    testValidationRegex: "^sk(_sbox)?_(.+)$",
    liveExpectedFormat:
      "API secret key should begin with sk_ and not begin with sk_sbox_",
    testExpectedFormat: "API secret key should begin with sk_",
  },
];

var checkoutInfo = {
  description:
    "Streamlined processor offering multiple payment options for a seamless checkout experience.",
  validate: checkoutInfo_validate,
};

var braintreeInfo = {
  description:
    "Trusted processor supporting credit cards, e-checks, and mobile payments for secure online transactions.",
};

var klarnaInfo = {
  description:
    "Flexible processor offering buy now, pay later options, and seamless checkout experiences for shoppers.",
  inputFieldDescription:
    "Please enter API Key in this format: Basic {API Key}\n\nEx: If your API key is UE4wO please enter Basic UE4wO",
};

var authorizedotnetInfo = {
  description:
    "Trusted processor supporting credit cards, e-checks, and mobile payments for secure online transactions.",
};

var globalpayInfo = {
  description:
    "Comprehensive processor providing global payment solutions for businesses of all sizes.",
};

var bluesnapInfo = {
  description:
    "All-in-one processor supporting global payment methods, subscription billing, and built-in fraud prevention.",
};

var airwallexInfo = {
  description:
    "Innovative processor enabling businesses to manage cross-border payments and foreign exchange seamlessly.",
};

var worldpayInfo = {
  description:
    "Leading processor facilitating secure online and in-person payments with global coverage and a range of payment options.",
};

var cybersourceInfo = {
  description:
    "Reliable processor providing fraud management tools, secure payment processing, and a variety of payment methods.",
};

var aciInfo = {
  description:
    "Trusted processor offering a wide range of payment solutions, including cards, digital wallets, and real-time bank transfers.",
};

var worldlineInfo = {
  description:
    "Comprehensive processor supporting secure payment acceptance across various channels and devices with advanced security features.",
};

var fiservInfo = {
  description:
    "Full-service processor offering secure payment solutions and innovative banking technologies for businesses of all sizes.",
};

var shift4Info = {
  description:
    "Integrated processor providing secure payment processing, advanced fraud prevention, and comprehensive reporting and analytics.",
};

var rapydInfo = {
  description:
    "Flexible processor enabling businesses to accept and disburse payments globally with a wide range of payment methods.",
};

var payuInfo = {
  description:
    "Reliable processor offering easy integration, multiple payment methods, and localized solutions for global businesses.",
};

var nuveiInfo = {
  description:
    "Payment technology company providing flexible, scalable, and secure payment solutions for businesses across various industries.",
};

var dlocalInfo = {
  description:
    "Cross-border payment processor enabling businesses to accept and send payments in emerging markets worldwide.",
};

var multisafepayInfo = {
  description:
    "Versatile processor supporting a wide range of payment methods, including credit cards, e-wallets, and online banking.",
};

var bamboraInfo = {
  description:
    "Comprehensive processor offering secure payment solutions and advanced features for businesses in various industries.",
};

var zenInfo = {
  description:
    "Modern processor providing seamless payment solutions with a focus on simplicity, security, and user experience.",
};

var mollieInfo = {
  description:
    "Developer-friendly processor providing simple and customizable payment solutions for businesses of all sizes.",
};

var trustpayInfo = {
  description:
    "Reliable processor offering secure online payment solutions, including credit cards, bank transfers, and e-wallets.",
};

var paypalInfo = {
  description:
    "Well-known processor enabling individuals and businesses to send, receive, and manage online payments securely.",
};

var coinbaseInfo = {
  description:
    "Cryptocurrency processor allowing businesses to accept digital currencies like Bitcoin, Ethereum, and more.",
};

var openNodeInfo = {
  description:
    "Bitcoin payment processor enabling businesses to accept Bitcoin payments and settle in their local currency.",
};

var nmiInfo = {
  description:
    "Versatile payment processor supporting various payment methods and offering advanced customization and integration capabilities.",
};

var iataPayInfo = {
  description:
    "IATA Pay is an alternative method for travelers to pay for air tickets purchased online by directly debiting their bank account. It improves speed and security of payments, while reducing payment costs.",
};

var bitPayInfo = {
  description:
    "BitPay is a payment service provider that allows businesses and individuals to accept and process payments in Bitcoin and other cryptocurrencies securely and conveniently.",
};

var nexinetsInfo = {
  description:
    "Leading Italian payment processor providing a wide range of payment solutions for businesses of all sizes.",
};

var forteInfo = {
  description:
    "Payment processor specializing in secure and reliable payment solutions for variuos industries like healthcare.",
};

var cryptopayInfo = {
  description:
    "Secure cryptocurrency payment solution. Simplify transactions with digital currencies. Convenient and reliable.",
};

var cashToCodeInfo = {
  description:
    "Secure cash-based payment solution. Generate barcode, pay with cash at retail. Convenient alternative for cash transactions online.",
};

var powertranzInfo = {
  description:
    "Versatile processor empowering businesses with flexible payment solutions for online and mobile transactions.",
};

var paymeInfo = {
  description:
    "Convenient and secure mobile payment solution for quick transactions anytime, anywhere.",
};

var globepayInfo = {
  description:
    "Global gateway for seamless cross-border payments, ensuring efficient transactions worldwide.",
};

var tsysInfo = {
  description:
    "Trusted provider offering reliable payment processing services to businesses of all sizes across the globe.",
};

var noonInfo = {
  description:
    "A leading fintech company revolutionizing payments with innovative, secure, and convenient solutions for seamless financial transactions.",
};

var pretendpayInfo = {
  description:
    "Don't be fooled by the name - PretendPay is the real deal when it comes to testing your payments.",
};

var fauxpayInfo = {
  description:
    "Don't worry, it's not really fake - it's just FauxPay! Use it to simulate payments and refunds.",
};

var phonypayInfo = {
  description:
    "Don't want to use real money to test your payment flow? - PhonyPay lets you simulate payments and refunds",
};

var stripeTestInfo = {
  description:
    "A stripe test processor to test payments and refunds without real world consequences.",
};

var paypalTestInfo = {
  description:
    "A paypal test processor to simulate payment flows and experience hyperswitch checkout.",
};

var wiseInfo = {
  description:
    "Get your money moving internationally. Save up to 3.9x when you send with Wise.",
};

var staxInfo = {
  description:
    "Empowering businesses with effortless payment solutions for truly seamless transactions",
};

var voltInfo = {
  description:
    "A secure and versatile payment processor that facilitates seamless electronic transactions for businesses and individuals, offering a wide range of payment options and robust fraud protection.",
};

var prophetpayInfo = {
  description:
    "A secure, affordable, and easy-to-use credit card processing platform for any business.",
};

var helcimInfo = {
  description:
    "Helcim is the easy and affordable solution for small businesses accepting credit card payments.",
};

var threedsecuredotioInfo = {
  description:
    "A secure, affordable and easy to connect 3DS authentication platform. Improve the user experience during checkout, enhance the conversion rates and stay compliant with the regulations with 3dsecure.io",
};

var netceteraInfo = {
  description:
    "Cost-effective 3DS authentication platform ensuring security. Elevate checkout experience, boost conversion rates, and maintain regulatory compliance with Netcetera",
};

var unknownConnectorInfo = {
  description: "unkown connector",
};

var bankOfAmericaInfo = {
  description:
    "A top financial firm offering banking, investing, and risk solutions to individuals and businesses.",
};

var placetopayInfo = {
  description:
    "Reliable payment processor facilitating secure transactions online for businesses, ensuring seamless transactions.",
};

var billwerkInfo = {
  description:
    "Billwerk+ Pay is an acquirer independent payment gateway that helps you get the best acquirer rates, select a wide variety of payment methods.",
};

var zslInfo = {
  description:
    "It is a payment processor that enables businesses to accept payments securely through local bank transfers.",
};

function getThreeDsAuthenticatorNameString(threeDsAuthenticator) {
  if (threeDsAuthenticator) {
    return "netcetera";
  } else {
    return "threedsecureio";
  }
}

function getConnectorNameString(connector) {
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      var connector$1 = connector._0;
      switch (connector$1) {
        case /* ADYEN */ 0:
          return "adyen";
        case /* CHECKOUT */ 1:
          return "checkout";
        case /* BRAINTREE */ 2:
          return "braintree";
        case /* BANKOFAMERICA */ 3:
          return "bankofamerica";
        case /* BILLWERK */ 4:
          return "billwerk";
        case /* AUTHORIZEDOTNET */ 5:
          return "authorizedotnet";
        case /* STRIPE */ 6:
          return "stripe";
        case /* KLARNA */ 7:
          return "klarna";
        case /* GLOBALPAY */ 8:
          return "globalpay";
        case /* BLUESNAP */ 9:
          return "bluesnap";
        case /* AIRWALLEX */ 10:
          return "airwallex";
        case /* WORLDPAY */ 11:
          return "worldpay";
        case /* CYBERSOURCE */ 12:
          return "cybersource";
        case /* ACI */ 13:
          return "aci";
        case /* WORLDLINE */ 14:
          return "worldline";
        case /* FISERV */ 15:
          return "fiserv";
        case /* SHIFT4 */ 16:
          return "shift4";
        case /* RAPYD */ 17:
          return "rapyd";
        case /* PAYU */ 18:
          return "payu";
        case /* NUVEI */ 19:
          return "nuvei";
        case /* DLOCAL */ 20:
          return "dlocal";
        case /* MULTISAFEPAY */ 21:
          return "multisafepay";
        case /* BAMBORA */ 22:
          return "bambora";
        case /* MOLLIE */ 23:
          return "mollie";
        case /* TRUSTPAY */ 24:
          return "trustpay";
        case /* ZEN */ 25:
          return "zen";
        case /* PAYPAL */ 26:
          return "paypal";
        case /* COINBASE */ 27:
          return "coinbase";
        case /* OPENNODE */ 28:
          return "opennode";
        case /* PHONYPAY */ 29:
          return "phonypay";
        case /* FAUXPAY */ 30:
          return "fauxpay";
        case /* PRETENDPAY */ 31:
          return "pretendpay";
        case /* NMI */ 32:
          return "nmi";
        case /* FORTE */ 33:
          return "forte";
        case /* NEXINETS */ 34:
          return "nexinets";
        case /* IATAPAY */ 35:
          return "iatapay";
        case /* BITPAY */ 36:
          return "bitpay";
        case /* CRYPTOPAY */ 37:
          return "cryptopay";
        case /* CASHTOCODE */ 38:
          return "cashtocode";
        case /* PAYME */ 39:
          return "payme";
        case /* GLOBEPAY */ 40:
          return "globepay";
        case /* POWERTRANZ */ 41:
          return "powertranz";
        case /* TSYS */ 42:
          return "tsys";
        case /* NOON */ 43:
          return "noon";
        case /* STRIPE_TEST */ 44:
          return "stripe_test";
        case /* PAYPAL_TEST */ 45:
          return "paypal_test";
        case /* STAX */ 46:
          return "stax";
        case /* WISE */ 47:
          return "wise";
        case /* GOCARDLESS */ 48:
          return "gocardless";
        case /* VOLT */ 49:
          return "volt";
        case /* PROPHETPAY */ 50:
          return "prophetpay";
        case /* HELCIM */ 51:
          return "helcim";
        case /* PLACETOPAY */ 52:
          return "placetopay";
        case /* ZSL */ 53:
          return "zsl";
      }
    case /* ThreeDsAuthenticator */ 1:
      if (connector._0) {
        return "netcetera";
      } else {
        return "threedsecureio";
      }
    case /* UnknownConnector */ 2:
      return connector._0;
  }
}

function getConnectorNameTypeFromString(connector, connectorTypeOpt, param) {
  var connectorType =
    connectorTypeOpt !== undefined ? connectorTypeOpt : /* Processor */ 1;
  if (connectorType === 0) {
    return {
      TAG: /* UnknownConnector */ 2,
      _0: "Not known",
    };
  }
  switch (connectorType) {
    case /* Processor */ 1:
      switch (connector) {
        case "aci":
          return {
            TAG: /* Processors */ 0,
            _0: /* ACI */ 13,
          };
        case "adyen":
          return {
            TAG: /* Processors */ 0,
            _0: /* ADYEN */ 0,
          };
        case "airwallex":
          return {
            TAG: /* Processors */ 0,
            _0: /* AIRWALLEX */ 10,
          };
        case "authorizedotnet":
          return {
            TAG: /* Processors */ 0,
            _0: /* AUTHORIZEDOTNET */ 5,
          };
        case "bambora":
          return {
            TAG: /* Processors */ 0,
            _0: /* BAMBORA */ 22,
          };
        case "bankofamerica":
          return {
            TAG: /* Processors */ 0,
            _0: /* BANKOFAMERICA */ 3,
          };
        case "billwerk":
          return {
            TAG: /* Processors */ 0,
            _0: /* BILLWERK */ 4,
          };
        case "bitpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* BITPAY */ 36,
          };
        case "bluesnap":
          return {
            TAG: /* Processors */ 0,
            _0: /* BLUESNAP */ 9,
          };
        case "braintree":
          return {
            TAG: /* Processors */ 0,
            _0: /* BRAINTREE */ 2,
          };
        case "cashtocode":
          return {
            TAG: /* Processors */ 0,
            _0: /* CASHTOCODE */ 38,
          };
        case "checkout":
          return {
            TAG: /* Processors */ 0,
            _0: /* CHECKOUT */ 1,
          };
        case "coinbase":
          return {
            TAG: /* Processors */ 0,
            _0: /* COINBASE */ 27,
          };
        case "cryptopay":
          return {
            TAG: /* Processors */ 0,
            _0: /* CRYPTOPAY */ 37,
          };
        case "cybersource":
          return {
            TAG: /* Processors */ 0,
            _0: /* CYBERSOURCE */ 12,
          };
        case "dlocal":
          return {
            TAG: /* Processors */ 0,
            _0: /* DLOCAL */ 20,
          };
        case "fauxpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* FAUXPAY */ 30,
          };
        case "fiserv":
          return {
            TAG: /* Processors */ 0,
            _0: /* FISERV */ 15,
          };
        case "forte":
          return {
            TAG: /* Processors */ 0,
            _0: /* FORTE */ 33,
          };
        case "globalpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* GLOBALPAY */ 8,
          };
        case "globepay":
          return {
            TAG: /* Processors */ 0,
            _0: /* GLOBEPAY */ 40,
          };
        case "gocardless":
          return {
            TAG: /* Processors */ 0,
            _0: /* GOCARDLESS */ 48,
          };
        case "helcim":
          return {
            TAG: /* Processors */ 0,
            _0: /* HELCIM */ 51,
          };
        case "iatapay":
          return {
            TAG: /* Processors */ 0,
            _0: /* IATAPAY */ 35,
          };
        case "klarna":
          return {
            TAG: /* Processors */ 0,
            _0: /* KLARNA */ 7,
          };
        case "mollie":
          return {
            TAG: /* Processors */ 0,
            _0: /* MOLLIE */ 23,
          };
        case "multisafepay":
          return {
            TAG: /* Processors */ 0,
            _0: /* MULTISAFEPAY */ 21,
          };
        case "nexinets":
          return {
            TAG: /* Processors */ 0,
            _0: /* NEXINETS */ 34,
          };
        case "nmi":
          return {
            TAG: /* Processors */ 0,
            _0: /* NMI */ 32,
          };
        case "noon":
          return {
            TAG: /* Processors */ 0,
            _0: /* NOON */ 43,
          };
        case "nuvei":
          return {
            TAG: /* Processors */ 0,
            _0: /* NUVEI */ 19,
          };
        case "opennode":
          return {
            TAG: /* Processors */ 0,
            _0: /* OPENNODE */ 28,
          };
        case "payme":
          return {
            TAG: /* Processors */ 0,
            _0: /* PAYME */ 39,
          };
        case "paypal":
          return {
            TAG: /* Processors */ 0,
            _0: /* PAYPAL */ 26,
          };
        case "paypal_test":
          return {
            TAG: /* Processors */ 0,
            _0: /* PAYPAL_TEST */ 45,
          };
        case "payu":
          return {
            TAG: /* Processors */ 0,
            _0: /* PAYU */ 18,
          };
        case "phonypay":
          return {
            TAG: /* Processors */ 0,
            _0: /* PHONYPAY */ 29,
          };
        case "placetopay":
          return {
            TAG: /* Processors */ 0,
            _0: /* PLACETOPAY */ 52,
          };
        case "powertranz":
          return {
            TAG: /* Processors */ 0,
            _0: /* POWERTRANZ */ 41,
          };
        case "pretendpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* PRETENDPAY */ 31,
          };
        case "prophetpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* PROPHETPAY */ 50,
          };
        case "rapyd":
          return {
            TAG: /* Processors */ 0,
            _0: /* RAPYD */ 17,
          };
        case "shift4":
          return {
            TAG: /* Processors */ 0,
            _0: /* SHIFT4 */ 16,
          };
        case "stax":
          return {
            TAG: /* Processors */ 0,
            _0: /* STAX */ 46,
          };
        case "stripe":
          return {
            TAG: /* Processors */ 0,
            _0: /* STRIPE */ 6,
          };
        case "stripe_test":
          return {
            TAG: /* Processors */ 0,
            _0: /* STRIPE_TEST */ 44,
          };
        case "trustpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* TRUSTPAY */ 24,
          };
        case "tsys":
          return {
            TAG: /* Processors */ 0,
            _0: /* TSYS */ 42,
          };
        case "volt":
          return {
            TAG: /* Processors */ 0,
            _0: /* VOLT */ 49,
          };
        case "wise":
          return {
            TAG: /* Processors */ 0,
            _0: /* WISE */ 47,
          };
        case "worldline":
          return {
            TAG: /* Processors */ 0,
            _0: /* WORLDLINE */ 14,
          };
        case "worldpay":
          return {
            TAG: /* Processors */ 0,
            _0: /* WORLDPAY */ 11,
          };
        case "zen":
          return {
            TAG: /* Processors */ 0,
            _0: /* ZEN */ 25,
          };
        case "zsl":
          return {
            TAG: /* Processors */ 0,
            _0: /* ZSL */ 53,
          };
        default:
          return {
            TAG: /* UnknownConnector */ 2,
            _0: "Not known",
          };
      }
    case /* PayoutConnector */ 2:
      return {
        TAG: /* UnknownConnector */ 2,
        _0: "Not known",
      };
    case /* ThreeDsAuthenticator */ 3:
      switch (connector) {
        case "netcetera":
          return {
            TAG: /* ThreeDsAuthenticator */ 1,
            _0: /* NETCETERA */ 1,
          };
        case "threedsecureio":
          return {
            TAG: /* ThreeDsAuthenticator */ 1,
            _0: /* THREEDSECUREIO */ 0,
          };
        default:
          return {
            TAG: /* UnknownConnector */ 2,
            _0: "Not known",
          };
      }
  }
}

function getProcessorInfo(connector) {
  switch (connector) {
    case /* ADYEN */ 0:
      return adyenInfo;
    case /* CHECKOUT */ 1:
      return checkoutInfo;
    case /* BRAINTREE */ 2:
      return braintreeInfo;
    case /* BANKOFAMERICA */ 3:
      return bankOfAmericaInfo;
    case /* BILLWERK */ 4:
      return billwerkInfo;
    case /* AUTHORIZEDOTNET */ 5:
      return authorizedotnetInfo;
    case /* STRIPE */ 6:
      return stripeInfo;
    case /* KLARNA */ 7:
      return klarnaInfo;
    case /* GLOBALPAY */ 8:
      return globalpayInfo;
    case /* BLUESNAP */ 9:
      return bluesnapInfo;
    case /* AIRWALLEX */ 10:
      return airwallexInfo;
    case /* WORLDPAY */ 11:
      return worldpayInfo;
    case /* CYBERSOURCE */ 12:
      return cybersourceInfo;
    case /* ACI */ 13:
      return aciInfo;
    case /* WORLDLINE */ 14:
      return worldlineInfo;
    case /* FISERV */ 15:
      return fiservInfo;
    case /* SHIFT4 */ 16:
      return shift4Info;
    case /* RAPYD */ 17:
      return rapydInfo;
    case /* PAYU */ 18:
      return payuInfo;
    case /* NUVEI */ 19:
      return nuveiInfo;
    case /* DLOCAL */ 20:
      return dlocalInfo;
    case /* MULTISAFEPAY */ 21:
      return multisafepayInfo;
    case /* BAMBORA */ 22:
      return bamboraInfo;
    case /* MOLLIE */ 23:
      return mollieInfo;
    case /* TRUSTPAY */ 24:
      return trustpayInfo;
    case /* ZEN */ 25:
      return zenInfo;
    case /* PAYPAL */ 26:
      return paypalInfo;
    case /* COINBASE */ 27:
      return coinbaseInfo;
    case /* OPENNODE */ 28:
      return openNodeInfo;
    case /* PHONYPAY */ 29:
      return phonypayInfo;
    case /* FAUXPAY */ 30:
      return fauxpayInfo;
    case /* PRETENDPAY */ 31:
      return pretendpayInfo;
    case /* NMI */ 32:
      return nmiInfo;
    case /* FORTE */ 33:
      return forteInfo;
    case /* NEXINETS */ 34:
      return nexinetsInfo;
    case /* IATAPAY */ 35:
      return iataPayInfo;
    case /* BITPAY */ 36:
      return bitPayInfo;
    case /* CRYPTOPAY */ 37:
      return cryptopayInfo;
    case /* CASHTOCODE */ 38:
      return cashToCodeInfo;
    case /* PAYME */ 39:
      return paymeInfo;
    case /* GLOBEPAY */ 40:
      return globepayInfo;
    case /* POWERTRANZ */ 41:
      return powertranzInfo;
    case /* TSYS */ 42:
      return tsysInfo;
    case /* NOON */ 43:
      return noonInfo;
    case /* STRIPE_TEST */ 44:
      return stripeTestInfo;
    case /* PAYPAL_TEST */ 45:
      return paypalTestInfo;
    case /* STAX */ 46:
      return staxInfo;
    case /* WISE */ 47:
      return wiseInfo;
    case /* GOCARDLESS */ 48:
      return goCardLessInfo;
    case /* VOLT */ 49:
      return voltInfo;
    case /* PROPHETPAY */ 50:
      return prophetpayInfo;
    case /* HELCIM */ 51:
      return helcimInfo;
    case /* PLACETOPAY */ 52:
      return placetopayInfo;
    case /* ZSL */ 53:
      return zslInfo;
  }
}

function getThreedsAuthenticatorInfo(threeDsAuthenticator) {
  if (threeDsAuthenticator) {
    return netceteraInfo;
  } else {
    return threedsecuredotioInfo;
  }
}

function getConnectorInfo(connector) {
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      return getProcessorInfo(connector._0);
    case /* ThreeDsAuthenticator */ 1:
      if (connector._0) {
        return netceteraInfo;
      } else {
        return threedsecuredotioInfo;
      }
    case /* UnknownConnector */ 2:
      return unknownConnectorInfo;
  }
}

function acceptedValues(dict) {
  var values_type = LogicUtils.getString(dict, "type", "enable_only");
  var values_list = LogicUtils.getStrArray(dict, "list");
  var values = {
    type: values_type,
    list: values_list,
  };
  if (values_list.length > 0) {
    return values;
  }
}

function itemProviderMapper(dict) {
  return {
    payment_method_type: LogicUtils.getString(dict, "payment_method_type", ""),
    card_networks: LogicUtils.getStrArrayFromDict(dict, "card_networks", []),
    accepted_currencies: acceptedValues(
      LogicUtils.getDictfromDict(dict, "accepted_currencies"),
    ),
    accepted_countries: acceptedValues(
      LogicUtils.getDictfromDict(dict, "accepted_countries"),
    ),
    minimum_amount: LogicUtils.getOptionInt(dict, "minimum_amount"),
    maximum_amount: LogicUtils.getOptionInt(dict, "maximum_amount"),
    recurring_enabled: LogicUtils.getOptionBool(dict, "recurring_enabled"),
    installment_payment_enabled: LogicUtils.getOptionBool(
      dict,
      "installment_payment_enabled",
    ),
    payment_experience: LogicUtils.getOptionString(dict, "payment_method_type"),
  };
}

function getPaymentMethodMapper(json) {
  return LogicUtils.getArrayDataFromJson(json, itemProviderMapper);
}

function itemToObjMapper(dict) {
  return {
    payment_method: LogicUtils.getString(dict, "payment_method", ""),
    payment_method_type: LogicUtils.getString(dict, "payment_method_type", ""),
    provider: LogicUtils.getArrayDataFromJson(
      LogicUtils.getArrayFromDict(dict, "provider", []),
      itemProviderMapper,
    ),
    card_provider: LogicUtils.getArrayDataFromJson(
      LogicUtils.getArrayFromDict(dict, "card_provider", []),
      itemProviderMapper,
    ),
  };
}

function getPaymentMethodEnabled(json) {
  return LogicUtils.getArrayDataFromJson(json, itemToObjMapper);
}

var connectorIgnoredField = [
  "business_country",
  "business_label",
  "business_sub_label",
  "merchant_connector_id",
  "connector_name",
  "profile_id",
  "applepay_verified_domains",
];

var configKeysToIgnore = [
  "connector_auth",
  "is_verifiable",
  "metadata",
  "connector_webhook_details",
];

var verifyConnectorIgnoreField = [
  "business_country",
  "business_label",
  "business_sub_label",
  "merchant_connector_id",
  "applepay_verified_domains",
];

function ignoreFields(json, id, fields) {
  if (id.length <= 0 || id === "new") {
    return json;
  } else {
    return LogicUtils.getJsonFromArrayOfJson(
      Object.entries(LogicUtils.getDictFromJsonObject(json)).filter(
        function (entry) {
          return !fields.includes(entry[0]);
        },
      ),
    );
  }
}

function mapAuthType(authType) {
  var match = authType.toLowerCase();
  switch (match) {
    case "bodykey":
      return "BodyKey";
    case "currencyauthkey":
      return "CurrencyAuthKey";
    case "headerkey":
      return "HeaderKey";
    case "multiauthkey":
      return "MultiAuthKey";
    case "signaturekey":
      return "SignatureKey";
    case "temporaryauth":
      return "TemporaryAuth";
    default:
      return "Nokey";
  }
}

function getConnectorType(connector, isPayoutFlow, param) {
  if (isPayoutFlow) {
    return "payout_processor";
  }
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      return "payment_processor";
    case /* ThreeDsAuthenticator */ 1:
      return "authentication_processor";
    case /* UnknownConnector */ 2:
      return connector._0;
  }
}

function getSelectedPaymentObj(paymentMethodsEnabled, paymentMethod) {
  return Core__Option.getOr(
    paymentMethodsEnabled.find(function (item) {
      return (
        item.payment_method_type.toLowerCase() === paymentMethod.toLowerCase()
      );
    }),
    {
      payment_method: "unknown",
      payment_method_type: "unkonwn",
    },
  );
}

function addMethod(paymentMethodsEnabled, paymentMethod, method) {
  var pmts = paymentMethodsEnabled.slice();
  var match = getPaymentMethodFromString(paymentMethod);
  if (match === 0) {
    pmts.forEach(function (val) {
      if (
        val.payment_method_type.toLowerCase() === paymentMethod.toLowerCase()
      ) {
        Core__Option.getOr(
          val.card_provider,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ).push(method);
        return;
      }
    });
  } else {
    pmts.forEach(function (val) {
      if (
        val.payment_method_type.toLowerCase() === paymentMethod.toLowerCase()
      ) {
        Core__Option.getOr(
          val.provider,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ).push(method);
        return;
      }
    });
  }
  return pmts;
}

function removeMethod(paymentMethodsEnabled, paymentMethod, method) {
  var pmts = paymentMethodsEnabled.slice();
  var match = getPaymentMethodFromString(paymentMethod);
  if (match === 0) {
    pmts.forEach(function (val) {
      if (
        val.payment_method_type.toLowerCase() !== paymentMethod.toLowerCase()
      ) {
        return;
      }
      var indexOfRemovalItem = Core__Option.getOr(
        val.card_provider,
        LogicUtils.getArrayDataFromJson([], itemProviderMapper),
      )
        .map(function (ele) {
          return ele.payment_method_type;
        })
        .indexOf(method.payment_method_type);
      Caml_splice_call.spliceObjApply(
        Core__Option.getOr(
          val.card_provider,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ),
        "splice",
        [
          indexOfRemovalItem,
          1,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ],
      );
    });
  } else {
    pmts.forEach(function (val) {
      if (
        val.payment_method_type.toLowerCase() !== paymentMethod.toLowerCase()
      ) {
        return;
      }
      var indexOfRemovalItem = Core__Option.getOr(
        val.provider,
        LogicUtils.getArrayDataFromJson([], itemProviderMapper),
      )
        .map(function (ele) {
          return ele.payment_method_type;
        })
        .indexOf(method.payment_method_type);
      Caml_splice_call.spliceObjApply(
        Core__Option.getOr(
          val.provider,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ),
        "splice",
        [
          indexOfRemovalItem,
          1,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ],
      );
    });
  }
  return pmts;
}

function generateInitialValuesDict(
  values,
  connector,
  bodyType,
  isPayoutFlowOpt,
  isLiveModeOpt,
  connectorTypeOpt,
  param,
) {
  var isPayoutFlow = isPayoutFlowOpt !== undefined ? isPayoutFlowOpt : false;
  var isLiveMode = isLiveModeOpt !== undefined ? isLiveModeOpt : false;
  var connectorType =
    connectorTypeOpt !== undefined ? connectorTypeOpt : /* Processor */ 1;
  var dict = LogicUtils.getDictFromJsonObject(values);
  var connectorAccountDetails = LogicUtils.getDictFromJsonObject(
    LogicUtils.getJsonObjectFromDict(dict, "connector_account_details"),
  );
  connectorAccountDetails["auth_type"] = bodyType;
  dict["connector_account_details"] = connectorAccountDetails;
  dict["connector_name"] = connector;
  dict["connector_type"] = getConnectorType(
    getConnectorNameTypeFromString(connector, connectorType, undefined),
    isPayoutFlow,
    undefined,
  );
  dict["disabled"] = LogicUtils.getBool(dict, "disabled", false);
  dict["test_mode"] = isLiveMode ? false : true;
  dict["connector_label"] = LogicUtils.getString(dict, "connector_label", "");
  var connectorWebHookDetails = LogicUtils.getDictFromJsonObject(
    LogicUtils.getJsonObjectFromDict(dict, "connector_webhook_details"),
  );
  dict["connector_webhook_details"] = Core__Option.isSome(
    LogicUtils.getOptionString(connectorWebHookDetails, "merchant_secret"),
  )
    ? connectorWebHookDetails
    : null;
  return dict;
}

function getDisableConnectorPayload(connectorType, previousConnectorState) {
  return Object.fromEntries([
    ["connector_type", connectorType],
    ["disabled", !previousConnectorState],
  ]);
}

function getWebHookRequiredFields(connector, fieldName) {
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      if (connector._0 !== 0 || fieldName !== "merchant_secret") {
        return false;
      } else {
        return true;
      }
    case /* ThreeDsAuthenticator */ 1:
    case /* UnknownConnector */ 2:
      return false;
  }
}

function getMetaDataRequiredFields(connector, fieldName) {
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      var match = connector._0;
      if (!(match > 31 || match < 2)) {
        if (match !== 9 || fieldName !== "merchant_id") {
          return true;
        } else {
          return false;
        }
      }
      if (match > 32 || match < 1) {
        return true;
      }
      switch (fieldName) {
        case "acquirer_bin":
        case "acquirer_merchant_id":
          return false;
        default:
          return true;
      }
    case /* ThreeDsAuthenticator */ 1:
      if (
        connector._0 ||
        fieldName !== "pull_mechanism_for_external_3ds_enabled"
      ) {
        return true;
      } else {
        return false;
      }
    case /* UnknownConnector */ 2:
      return true;
  }
}

function getAuthKeyMapFromConnectorAccountFields(connectorAccountFields) {
  return LogicUtils.convertMapObjectToDict(
    LogicUtils.getDictfromDict(connectorAccountFields, "auth_key_map"),
  );
}

function checkCashtoCodeFields(keys, country, valuesFlattenJson) {
  return keys.map(function (field) {
    var key =
      "connector_account_details.auth_key_map." + country + "." + field + "";
    var value = LogicUtils.getString(valuesFlattenJson, "" + key + "", "");
    return value.length !== 0;
  });
}

function checkCashtoCodeInnerField(valuesFlattenJson, dict, country) {
  var value = Object.keys(LogicUtils.getDictfromDict(dict, country));
  var result = value.map(function (method) {
    var keys = Object.keys(
      LogicUtils.getDictfromDict(
        LogicUtils.getDictfromDict(dict, country),
        method,
      ),
    );
    if (
      checkCashtoCodeFields(keys, country, valuesFlattenJson).includes(false)
    ) {
      return false;
    } else {
      return true;
    }
  });
  return result.includes(true);
}

function validateConnectorRequiredFields(
  connector,
  valuesFlattenJson,
  connectorAccountFields,
  connectorMetaDataFields,
  connectorWebHookDetails,
  connectorLabelDetailField,
  errors,
) {
  var newDict = LogicUtils.getDictFromJsonObject(errors);
  var exit = 0;
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      if (connector._0 !== 38) {
        exit = 1;
      } else {
        var dict = LogicUtils.convertMapObjectToDict(
          LogicUtils.getDictfromDict(connectorAccountFields, "auth_key_map"),
        );
        var indexLength = Object.keys(dict).length;
        var vector = Caml_array.make(indexLength, false);
        Object.keys(dict).forEach(function (country, index) {
          var res = checkCashtoCodeInnerField(valuesFlattenJson, dict, country);
          Caml_array.set(vector, index, res);
        });
        Js_vector.filterInPlace(function (val) {
          return val === true;
        }, vector);
        if (vector.length === 0) {
          newDict["Currency"] = "Please enter currency";
        }
      }
      break;
    case /* ThreeDsAuthenticator */ 1:
    case /* UnknownConnector */ 2:
      exit = 1;
      break;
  }
  if (exit === 1) {
    Object.keys(connectorAccountFields).forEach(function (value) {
      var key = "connector_account_details." + value + "";
      var errorKey = LogicUtils.getString(connectorAccountFields, value, "");
      var value$1 = LogicUtils.getString(
        valuesFlattenJson,
        "connector_account_details." + value + "",
        "",
      );
      if (value$1.length === 0) {
        newDict[key] = "Please enter " + errorKey + "";
        return;
      }
    });
  }
  Object.keys(connectorMetaDataFields).forEach(function (fieldName) {
    var walletType = getPaymentMethodTypeFromString(fieldName);
    if (
      !(walletType !== /* GooglePay */ 2 && walletType !== /* ApplePay */ 3)
    ) {
      return;
    }
    var key = "metadata." + fieldName + "";
    var errorKey = LogicUtils.getString(connectorMetaDataFields, fieldName, "");
    var value = LogicUtils.getString(
      valuesFlattenJson,
      "metadata." + fieldName + "",
      "",
    );
    if (value.length === 0 && getMetaDataRequiredFields(connector, fieldName)) {
      newDict[key] = "Please enter " + errorKey + "";
      return;
    }
  });
  Object.keys(connectorWebHookDetails).forEach(function (fieldName) {
    var key = "connector_webhook_details." + fieldName + "";
    var errorKey = LogicUtils.getString(connectorWebHookDetails, fieldName, "");
    var value = LogicUtils.getString(
      valuesFlattenJson,
      "connector_webhook_details." + fieldName + "",
      "",
    );
    if (value.length === 0 && getWebHookRequiredFields(connector, fieldName)) {
      newDict[key] = "Please enter " + errorKey + "";
      return;
    }
  });
  Object.keys(connectorLabelDetailField).forEach(function (fieldName) {
    var errorKey = LogicUtils.getString(
      connectorLabelDetailField,
      fieldName,
      "",
    );
    var value = LogicUtils.getString(valuesFlattenJson, fieldName, "");
    if (value.length === 0) {
      newDict[fieldName] = "Please enter " + errorKey + "";
      return;
    }
  });
  return newDict;
}

function getPlaceHolder(connector, fieldName, label) {
  switch (connector.TAG | 0) {
    case /* Processors */ 0:
      if (connector._0 === 7 && fieldName === "api_key") {
        return "Enter as:-Basic{API Key}";
      }
      break;
    case /* ThreeDsAuthenticator */ 1:
    case /* UnknownConnector */ 2:
      break;
  }
  return "Enter " + LogicUtils.snakeToTitle(label) + "";
}

function getConnectorDetailsValue(connectorInfo, str) {
  switch (str) {
    case "api_key":
      return connectorInfo.connector_account_details.api_key;
    case "api_secret":
      return connectorInfo.connector_account_details.api_secret;
    case "auth_type":
      return connectorInfo.connector_account_details.auth_type;
    case "key1":
      return connectorInfo.connector_account_details.key1;
    case "key2":
      return connectorInfo.connector_account_details.key2;
    default:
      return "";
  }
}

var connectorLabelDetailField = Object.fromEntries([
  ["connector_label", "Connector label"],
]);

function getConnectorFields(connectorDetails) {
  var connectorAccountDict = LogicUtils.getDictfromDict(
    LogicUtils.getDictFromJsonObject(connectorDetails),
    "connector_auth",
  );
  var bodyType = Core__Option.getOr(Object.keys(connectorAccountDict)[0], "");
  var connectorAccountFields = LogicUtils.getDictfromDict(
    connectorAccountDict,
    bodyType,
  );
  var connectorMetaDataFields = LogicUtils.getDictfromDict(
    LogicUtils.getDictFromJsonObject(connectorDetails),
    "metadata",
  );
  var isVerifyConnector = LogicUtils.getBool(
    LogicUtils.getDictFromJsonObject(connectorDetails),
    "is_verifiable",
    false,
  );
  var connectorWebHookDetails = LogicUtils.getDictfromDict(
    LogicUtils.getDictFromJsonObject(connectorDetails),
    "connector_webhook_details",
  );
  return [
    bodyType,
    connectorAccountFields,
    connectorMetaDataFields,
    isVerifyConnector,
    connectorWebHookDetails,
    connectorLabelDetailField,
  ];
}

function validateRequiredFiled(valuesFlattenJson, dict, fieldName, errors) {
  var newDict = LogicUtils.getDictFromJsonObject(errors);
  Object.keys(dict).forEach(function (_value) {
    var lastItem = Core__Option.getOr(fieldName.split(".").pop(), "");
    var errorKey = LogicUtils.getString(dict, lastItem, "");
    var value = LogicUtils.getString(
      valuesFlattenJson,
      "" + fieldName + "",
      "",
    );
    if (value.length === 0) {
      newDict[fieldName] = "Please enter " + errorKey + "";
      return;
    }
  });
  return newDict;
}

function validate(values, selectedConnector, dict, fieldName, isLiveMode) {
  var errors = {};
  var valuesFlattenJson = JsonFlattenUtils.flattenObject(values, true);
  var labelArr = Object.values(dict);
  Core__Option.getOr(selectedConnector.validate, []).forEach(
    function (field, index) {
      var key = field.name;
      var value = LogicUtils.getStringFromJson(
        Core__Option.getOr(valuesFlattenJson[key], ""),
        "",
      );
      var regexToUse = isLiveMode
        ? field.liveValidationRegex
        : field.testValidationRegex;
      var validationResult =
        regexToUse !== undefined ? new RegExp(regexToUse).test(value) : true;
      if (Core__Option.getOr(field.isRequired, true) && value.length === 0) {
        var errorLabel = LogicUtils.getStringFromJson(
          Core__Option.getOr(labelArr[index], ""),
          "",
        );
        errors[key] = "Please enter " + errorLabel + "";
        return;
      }
      if (!(!validationResult && value.length !== 0)) {
        return;
      }
      var expectedFormat = isLiveMode
        ? field.liveExpectedFormat
        : field.testExpectedFormat;
      var warningMessage = Core__Option.getOr(expectedFormat, "");
      errors[key] = warningMessage;
    },
  );
  var profileId = LogicUtils.getString(valuesFlattenJson, "profile_id", "");
  if (profileId.length === 0) {
    errors["Profile Id"] = "Please select your business profile";
  }
  return validateRequiredFiled(valuesFlattenJson, dict, fieldName, errors);
}

function getSuggestedAction(verifyErrorMessage, connector) {
  var msg = Core__Option.getOr(verifyErrorMessage, "");
  var match = getConnectorNameTypeFromString(connector, undefined, undefined);
  var match$1;
  switch (match.TAG | 0) {
    case /* Processors */ 0:
      var match$2 = match._0;
      match$1 =
        match$2 !== 6
          ? match$2 !== 26
            ? [null, false]
            : [
                msg.includes("Client Authentication failed")
                  ? React.createElement(
                      SuggestedActionHelper.PaypalClientAuthenticationFalied
                        .make,
                      {},
                    )
                  : null,
                true,
              ]
          : [
              msg.includes("Sending credit card numbers directly")
                ? React.createElement(
                    SuggestedActionHelper.StripSendingCreditCard.make,
                    {},
                  )
                : msg.includes("Invalid API Key")
                  ? React.createElement(
                      SuggestedActionHelper.StripeInvalidAPIKey.make,
                      {},
                    )
                  : null,
              true,
            ];
      break;
    case /* ThreeDsAuthenticator */ 1:
    case /* UnknownConnector */ 2:
      match$1 = [null, false];
      break;
  }
  return [match$1[0], match$1[1]];
}

async function onSubmit(
  values,
  onSubmitVerify,
  onSubmitMain,
  setVerifyDone,
  verifyDone,
  isVerifyConnector,
) {
  Curry._1(setVerifyDone, function (param) {
    return /* Loading */ 3;
  });
  if (verifyDone === /* NoAttempt */ 2 && isVerifyConnector) {
    Curry._1(onSubmitVerify, values);
  } else {
    Curry._1(onSubmitMain, values);
  }
  return null;
}

function getWebhooksUrl(connectorName, merchantId) {
  return (
    "" +
    window._env_.apiBaseUrl +
    "/webhooks/" +
    merchantId +
    "/" +
    connectorName +
    ""
  );
}

function constructConnectorRequestBody(wasmRequest, payload) {
  var dict = LogicUtils.getDictFromJsonObject(payload);
  var connectorAccountDetails = LogicUtils.getDictfromDict(
    dict,
    "connector_account_details",
  );
  var payLoadDetails_profile_id = LogicUtils.getString(dict, "profile_id", "");
  var payLoadDetails_connector_type = LogicUtils.getString(
    dict,
    "connector_type",
    "",
  );
  var payLoadDetails_connector_name = LogicUtils.getString(
    dict,
    "connector_name",
    "",
  );
  var payLoadDetails_disabled = LogicUtils.getBool(dict, "disabled", false);
  var payLoadDetails_test_mode = LogicUtils.getBool(dict, "test_mode", false);
  var payLoadDetails_connector_webhook_details = LogicUtils.isEmptyDict(
    LogicUtils.getDictfromDict(dict, "connector_webhook_details"),
  )
    ? undefined
    : Caml_option.some(
        LogicUtils.getDictfromDict(dict, "connector_webhook_details"),
      );
  var payLoadDetails = {
    profile_id: payLoadDetails_profile_id,
    connector_type: payLoadDetails_connector_type,
    connector_name: payLoadDetails_connector_name,
    connector_account_details: connectorAccountDetails,
    disabled: payLoadDetails_disabled,
    test_mode: payLoadDetails_test_mode,
    connector_webhook_details: payLoadDetails_connector_webhook_details,
  };
  var values = getRequestPayload(wasmRequest, payLoadDetails);
  var dict$1 = Object.fromEntries([
    ["connector_account_details", connectorAccountDetails],
    ["connector_label", LogicUtils.getString(dict, "connector_label", "")],
    ["status", LogicUtils.getString(dict, "status", "active")],
  ]);
  return Object.fromEntries(
    Object.entries(LogicUtils.getDictFromJsonObject(values)).concat(
      Object.entries(dict$1),
    ),
  );
}

function defaultSelectAllCards(
  pmts,
  isUpdateFlow,
  isPayoutFlow,
  connector,
  updateDetails,
) {
  if (isUpdateFlow) {
    return;
  }
  var config = LogicUtils.getDictFromJsonObject(
    isPayoutFlow
      ? window.getPayoutConnectorConfig(connector)
      : window.getConnectorConfig(connector),
  );
  pmts.forEach(function (val) {
    var match = getPaymentMethodFromString(val.payment_method);
    if (typeof match !== "number") {
      return;
    }
    switch (match) {
      case /* Card */ 0:
        var arr = LogicUtils.getArrayDataFromJson(
          LogicUtils.getArrayFromDict(config, val.payment_method_type, []),
          itemProviderMapper,
        );
        var length = Core__Option.getOr(
          val.card_provider,
          LogicUtils.getArrayDataFromJson([], itemProviderMapper),
        ).length;
        Caml_splice_call.spliceObjApply(
          Core__Option.getOr(
            val.card_provider,
            LogicUtils.getArrayDataFromJson([], itemProviderMapper),
          ),
          "splice",
          [0, length, arr],
        );
        return;
      case /* BankRedirect */ 3:
      case /* BankTransfer */ 4:
        break;
      case /* PayLater */ 1:
      case /* Wallet */ 2:
      case /* Crypto */ 5:
      case /* BankDebit */ 6:
        return;
    }
    var arr$1 = LogicUtils.getArrayDataFromJson(
      LogicUtils.getArrayFromDict(config, val.payment_method_type, []),
      itemProviderMapper,
    );
    var length$1 = Core__Option.getOr(
      val.provider,
      LogicUtils.getArrayDataFromJson([], itemProviderMapper),
    ).length;
    Caml_splice_call.spliceObjApply(
      Core__Option.getOr(
        val.provider,
        LogicUtils.getArrayDataFromJson([], itemProviderMapper),
      ),
      "splice",
      [0, length$1, arr$1],
    );
  });
  Curry._1(updateDetails, pmts);
}

async function getConnectorPaymentMethodDetails(
  initialValues,
  setPaymentMethods,
  setMetaData,
  isUpdateFlow,
  isPayoutFlow,
  connector,
  updateDetails,
) {
  try {
    var json = window.getResponsePayload(initialValues);
    var metaData = LogicUtils.getJsonObjectFromDict(
      LogicUtils.getDictFromJsonObject(json),
      "metadata",
    );
    var paymentMethodEnabled = LogicUtils.getArrayDataFromJson(
      LogicUtils.getJsonObjectFromDict(
        LogicUtils.getDictFromJsonObject(json),
        "payment_methods_enabled",
      ),
      itemToObjMapper,
    );
    Curry._1(setPaymentMethods, function (param) {
      return paymentMethodEnabled;
    });
    Curry._1(setMetaData, function (param) {
      return metaData;
    });
    return defaultSelectAllCards(
      paymentMethodEnabled,
      isUpdateFlow,
      isPayoutFlow,
      connector,
      updateDetails,
    );
  } catch (raw_e) {
    var e = Caml_js_exceptions.internalToOCamlException(raw_e);
    if (e.RE_EXN_ID === Js_exn.$$Error) {
      return Js_exn.raiseError(
        Core__Option.getOr(e._1.message, "Something went wrong"),
      );
    }
    throw e;
  }
}

function filterList(items, removeFromList) {
  return items.filter(function (dict) {
    var connectorType = dict.connector_type;
    var isPayoutConnector = connectorType === "payout_processor";
    var isThreeDsAuthenticator = connectorType === "authentication_processor";
    var isConnector =
      connectorType !== "payment_vas" &&
      !isPayoutConnector &&
      !isThreeDsAuthenticator;
    switch (removeFromList) {
      case /* FRMPlayer */ 0:
        return isConnector;
      case /* Processor */ 1:
        return !isConnector;
      case /* PayoutConnector */ 2:
        return isPayoutConnector;
      case /* ThreeDsAuthenticator */ 3:
        return isThreeDsAuthenticator;
    }
  });
}

function getProcessorsListFromJson(connnectorList, removeFromListOpt, param) {
  var removeFromList =
    removeFromListOpt !== undefined ? removeFromListOpt : /* FRMPlayer */ 0;
  return filterList(connnectorList, removeFromList);
}

function getDisplayNameForProcessor(connector) {
  switch (connector) {
    case /* ADYEN */ 0:
      return "Adyen";
    case /* CHECKOUT */ 1:
      return "Checkout";
    case /* BRAINTREE */ 2:
      return "Braintree";
    case /* BANKOFAMERICA */ 3:
      return "Bank of America";
    case /* BILLWERK */ 4:
      return "Billwerk";
    case /* AUTHORIZEDOTNET */ 5:
      return "Authorize.net";
    case /* STRIPE */ 6:
      return "Stripe";
    case /* KLARNA */ 7:
      return "Klarna";
    case /* GLOBALPAY */ 8:
      return "Global Payments";
    case /* BLUESNAP */ 9:
      return "Bluesnap";
    case /* AIRWALLEX */ 10:
      return "Airwallex";
    case /* WORLDPAY */ 11:
      return "Worldpay";
    case /* CYBERSOURCE */ 12:
      return "Cybersource";
    case /* ACI */ 13:
      return "ACI Worldwide";
    case /* WORLDLINE */ 14:
      return "Worldline";
    case /* FISERV */ 15:
      return "Fiserv";
    case /* SHIFT4 */ 16:
      return "Shift4";
    case /* RAPYD */ 17:
      return "Rapyd";
    case /* PAYU */ 18:
      return "PayU";
    case /* NUVEI */ 19:
      return "Nuvei";
    case /* DLOCAL */ 20:
      return "dLocal";
    case /* MULTISAFEPAY */ 21:
      return "MultiSafepay";
    case /* BAMBORA */ 22:
      return "Bambora";
    case /* MOLLIE */ 23:
      return "Mollie";
    case /* TRUSTPAY */ 24:
      return "TrustPay";
    case /* ZEN */ 25:
      return "Zen";
    case /* PAYPAL */ 26:
      return "PayPal";
    case /* COINBASE */ 27:
      return "Coinbase";
    case /* OPENNODE */ 28:
      return "Opennode";
    case /* PHONYPAY */ 29:
      return "Phony Pay";
    case /* FAUXPAY */ 30:
      return "Fauxpay";
    case /* PRETENDPAY */ 31:
      return "Pretendpay";
    case /* NMI */ 32:
      return "NMI";
    case /* FORTE */ 33:
      return "Forte";
    case /* NEXINETS */ 34:
      return "Nexinets";
    case /* IATAPAY */ 35:
      return "IATA Pay";
    case /* BITPAY */ 36:
      return "Bitpay";
    case /* CRYPTOPAY */ 37:
      return "Cryptopay";
    case /* CASHTOCODE */ 38:
      return "CashtoCode";
    case /* PAYME */ 39:
      return "PayMe";
    case /* GLOBEPAY */ 40:
      return "GlobePay";
    case /* POWERTRANZ */ 41:
      return "Powertranz";
    case /* TSYS */ 42:
      return "TSYS";
    case /* NOON */ 43:
      return "Noon";
    case /* STRIPE_TEST */ 44:
      return "Stripe Dummy";
    case /* PAYPAL_TEST */ 45:
      return "Paypal Dummy";
    case /* STAX */ 46:
      return "Stax";
    case /* WISE */ 47:
      return "Wise";
    case /* GOCARDLESS */ 48:
      return "GoCardless";
    case /* VOLT */ 49:
      return "Volt";
    case /* PROPHETPAY */ 50:
      return "Prophet Pay";
    case /* HELCIM */ 51:
      return "Helcim";
    case /* PLACETOPAY */ 52:
      return "Placetopay";
    case /* ZSL */ 53:
      return "ZSL";
  }
}

function getDisplayNameForThreedsAuthenticator(threeDsAuthenticator) {
  if (threeDsAuthenticator) {
    return "Netcetera";
  } else {
    return "3dsecure.io";
  }
}

function getDisplayNameForConnector(connectorTypeOpt, connector) {
  var connectorType =
    connectorTypeOpt !== undefined ? connectorTypeOpt : /* Processor */ 1;
  var connectorType$1 = getConnectorNameTypeFromString(
    connector.toLowerCase(),
    connectorType,
    undefined,
  );
  switch (connectorType$1.TAG | 0) {
    case /* Processors */ 0:
      return getDisplayNameForProcessor(connectorType$1._0);
    case /* ThreeDsAuthenticator */ 1:
      if (connectorType$1._0) {
        return "Netcetera";
      } else {
        return "3dsecure.io";
      }
    case /* UnknownConnector */ 2:
      return connectorType$1._0;
  }
}

function getConnectorTypeArrayFromListConnectors(
  connectorTypeOpt,
  connectorsList,
) {
  var connectorType =
    connectorTypeOpt !== undefined ? connectorTypeOpt : /* Processor */ 1;
  return connectorsList.map(function (connectorDetail) {
    return getConnectorNameTypeFromString(
      connectorDetail.connector_name,
      connectorType,
      undefined,
    );
  });
}

function connectorTypeStringToTypeMapper(connector_type) {
  switch (connector_type) {
    case "authentication_processor":
      return /* AuthenticationProcessor */ 3;
    case "payment_processor":
      return /* PaymentProcessor */ 0;
    case "payment_vas":
      return /* PaymentVas */ 1;
    case "payout_processor":
      return /* PayoutProcessor */ 2;
    default:
      return /* PaymentProcessor */ 0;
  }
}

function sortByName(c1, c2) {
  return LogicUtils.compareLogic(
    getConnectorNameString(c2),
    getConnectorNameString(c1),
  );
}

function existsInArray(element, connectorList) {
  return connectorList.some(function (e) {
    switch (e.TAG | 0) {
      case /* Processors */ 0:
        switch (element.TAG | 0) {
          case /* Processors */ 0:
            return e._0 === element._0;
          case /* ThreeDsAuthenticator */ 1:
          case /* UnknownConnector */ 2:
            return false;
        }
      case /* ThreeDsAuthenticator */ 1:
      case /* UnknownConnector */ 2:
        return false;
    }
  });
}

export {
  stepsArr,
  payoutStepsArr,
  getStepName,
  payoutConnectorList,
  threedsAuthenticatorList,
  connectorList,
  connectorListForLive,
  connectorListWithAutomaticFlow,
  getPaymentMethodFromString,
  getPaymentMethodTypeFromString,
  dummyConnectorList,
  checkIsDummyConnector,
  stripeInfo,
  goCardLessInfo,
  adyenInfo,
  checkoutInfo,
  braintreeInfo,
  klarnaInfo,
  authorizedotnetInfo,
  globalpayInfo,
  bluesnapInfo,
  airwallexInfo,
  worldpayInfo,
  cybersourceInfo,
  aciInfo,
  worldlineInfo,
  fiservInfo,
  shift4Info,
  rapydInfo,
  payuInfo,
  nuveiInfo,
  dlocalInfo,
  multisafepayInfo,
  bamboraInfo,
  zenInfo,
  mollieInfo,
  trustpayInfo,
  paypalInfo,
  coinbaseInfo,
  openNodeInfo,
  nmiInfo,
  iataPayInfo,
  bitPayInfo,
  nexinetsInfo,
  forteInfo,
  cryptopayInfo,
  cashToCodeInfo,
  powertranzInfo,
  paymeInfo,
  globepayInfo,
  tsysInfo,
  noonInfo,
  pretendpayInfo,
  fauxpayInfo,
  phonypayInfo,
  stripeTestInfo,
  paypalTestInfo,
  wiseInfo,
  staxInfo,
  voltInfo,
  prophetpayInfo,
  helcimInfo,
  threedsecuredotioInfo,
  netceteraInfo,
  unknownConnectorInfo,
  bankOfAmericaInfo,
  placetopayInfo,
  billwerkInfo,
  zslInfo,
  getThreeDsAuthenticatorNameString,
  getConnectorNameString,
  getConnectorNameTypeFromString,
  getProcessorInfo,
  getThreedsAuthenticatorInfo,
  getConnectorInfo,
  acceptedValues,
  itemProviderMapper,
  getPaymentMethodMapper,
  itemToObjMapper,
  getPaymentMethodEnabled,
  connectorIgnoredField,
  configKeysToIgnore,
  verifyConnectorIgnoreField,
  ignoreFields,
  mapAuthType,
  getConnectorType,
  getSelectedPaymentObj,
  addMethod,
  removeMethod,
  generateInitialValuesDict,
  getDisableConnectorPayload,
  getWebHookRequiredFields,
  getMetaDataRequiredFields,
  getAuthKeyMapFromConnectorAccountFields,
  checkCashtoCodeFields,
  checkCashtoCodeInnerField,
  validateConnectorRequiredFields,
  getPlaceHolder,
  getConnectorDetailsValue,
  connectorLabelDetailField,
  getConnectorFields,
  validateRequiredFiled,
  validate,
  getSuggestedAction,
  onSubmit,
  getWebhooksUrl,
  constructConnectorRequestBody,
  defaultSelectAllCards,
  getConnectorPaymentMethodDetails,
  filterList,
  getProcessorsListFromJson,
  getDisplayNameForProcessor,
  getDisplayNameForThreedsAuthenticator,
  getDisplayNameForConnector,
  getConnectorTypeArrayFromListConnectors,
  connectorTypeStringToTypeMapper,
  sortByName,
  existsInArray,
};
/* connectorLabelDetailField Not a pure module */
