// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Core__JSON from "@rescript/core/src/Core__JSON.bs.js";
import * as LogicUtils from "../utils/LogicUtils.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";

function getPaymentExperienceType(str) {
  switch (str) {
    case "invoke_sdk_client":
      return /* InvokeSDK */ 1;
    case "redirect_to_url":
      return /* RedirectToURL */ 0;
    default:
      return /* RedirectToURL */ 0;
  }
}

function getPaymentExperience(dict, str) {
  return Belt_Array.keepMap(
    Core__Option.getOr(
      Core__Option.flatMap(dict[str], Core__JSON.Decode.array),
      [],
    ),
    Core__JSON.Decode.object,
  ).map(function (json) {
    return {
      payment_experience_type: getPaymentExperienceType(
        LogicUtils.getString(json, "payment_experience_type", ""),
      ),
      eligible_connectors: LogicUtils.getStrArray(json, "eligible_connectors"),
    };
  });
}

function getBankNames(dict, str) {
  return Belt_Array.keepMap(
    Core__Option.getOr(
      Core__Option.flatMap(dict[str], Core__JSON.Decode.array),
      [],
    ),
    Core__JSON.Decode.object,
  ).map(function (json) {
    return {
      bank_name: LogicUtils.getStrArray(json, "bank_name"),
      eligible_connectors: LogicUtils.getStrArray(json, "eligible_connectors"),
    };
  });
}

function getAchConnectors(dict, str) {
  return LogicUtils.getStrArray(
    Core__Option.getOr(
      Core__Option.flatMap(dict[str], Core__JSON.Decode.object),
      {},
    ),
    "elligible_connectors",
  );
}

export {
  getPaymentExperienceType,
  getPaymentExperience,
  getBankNames,
  getAchConnectors,
};
/* LogicUtils Not a pure module */
