// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Clipboard from "../libraries/Clipboard.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as MonacoEditor from "../libraries/MonacoEditor.bs.js";
import * as AddDataAttributes from "./AddDataAttributes.bs.js";

function MonacoEditorLazy(props) {
  var outerWidth = props.outerWidth;
  var minimap = props.minimap;
  var showCopy = props.showCopy;
  var readOnly = props.readOnly;
  var value = props.value;
  var defaultValue = props.defaultValue;
  var readOnly$1 = readOnly !== undefined ? readOnly : false;
  var showCopy$1 = showCopy !== undefined ? showCopy : true;
  var minimap$1 = minimap !== undefined ? minimap : true;
  var outerWidth$1 = outerWidth !== undefined ? outerWidth : "w-full";
  var copyValue = Core__Option.isNone(value) ? defaultValue : value;
  return React.createElement(AddDataAttributes.make, {
    attributes: [
      ["data-editor", "Monaco Editor"],
      ["text", Core__Option.getOr(value, "")],
    ],
    children: React.createElement(
      "div",
      {
        className: "flex flex-col " + outerWidth$1 + "",
      },
      Core__Option.getOr(props.headerComponent, null),
      showCopy$1
        ? React.createElement(Clipboard.Copy.make, {
            data: copyValue,
          })
        : null,
      React.createElement(MonacoEditor.make, {
        defaultLanguage: props.defaultLanguage,
        defaultValue: defaultValue,
        value: value,
        height: props.height,
        theme: props.theme,
        width: props.width,
        options: {
          readOnly: readOnly$1,
          fontSize: Caml_option.some(props.fontSize),
          fontFamily: Caml_option.some(props.fontFamily),
          fontWeight: Caml_option.some(props.fontWeight),
          minimap: {
            enabled: minimap$1,
          },
        },
        onChange: props.onChange,
        onValidate: props.onValidate,
        onMount: props.onMount,
      }),
    ),
  });
}

var make = MonacoEditorLazy;

export { make };
/* react Not a pure module */
