// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Button from "./Button.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as NoDataFound from "./NoDataFound.bs.js";
import * as GlobalProvider from "../entryPoints/Provider/GlobalProvider.bs.js";
import * as HSwitchGlobalVars from "../utils/HSwitchGlobalVars.bs.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

function UnauthorizedPage(props) {
  var message = props.message;
  var message$1 =
    message !== undefined
      ? message
      : "You don't have access to this module. Contact admin for access";
  var match = React.useContext(GlobalProvider.defaultContext);
  var setDashboardPageState = match.setDashboardPageState;
  React.useEffect(function () {
    RescriptReactRouter.replace(
      HSwitchGlobalVars.appendDashboardPath("/unauthorized"),
    );
  }, []);
  return React.createElement(NoDataFound.make, {
    message: message$1,
    renderType: /* Locked */ 3,
    children: Caml_option.some(
      React.createElement(Button.make, {
        text: "Go to Home",
        buttonType: /* Primary */ 0,
        onClick: function (param) {
          Curry._1(setDashboardPageState, function (param) {
            return "HOME";
          });
          RescriptReactRouter.replace(
            HSwitchGlobalVars.appendDashboardPath("/home"),
          );
        },
        customButtonStyle: "mt-4 !p-2",
      }),
    ),
  });
}

var make = UnauthorizedPage;

export { make };
/* react Not a pure module */
