// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../../components/Icon.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Recoil from "recoil";
import * as APIUtils from "../APIUtils/APIUtils.bs.js";
import * as ACLButton from "../../components/ACLButton.bs.js";
import * as PageUtils from "../Utils/PageUtils.bs.js";
import * as PopUpState from "../../hooks/PopUpState.bs.js";
import * as ToastState from "../../hooks/ToastState.bs.js";
import * as Core__Option from "@rescript/core/src/Core__Option.bs.js";
import * as HyperswitchAtom from "../../Recoils/HyperswitchAtom.bs.js";
import * as HSwitchGlobalVars from "../../utils/HSwitchGlobalVars.bs.js";
import * as JsxPPXReactSupport from "rescript/lib/es6/jsxPPXReactSupport.js";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.bs.js";

var deleteSampleData = {
  heading: "Delete Sample Data",
  subHeading: "Delete all the generated sample data.",
  cardName: "DELETE_SAMPLE_DATA",
  buttonText: "Delete All",
  isApiCall: true,
};

function HSwitchSettings$TileComponent(props) {
  var cardName = props.cardName;
  var isApiCall = props.isApiCall;
  var redirectUrl = props.redirectUrl;
  var buttonText = props.buttonText;
  var isComingSoon = props.isComingSoon;
  var redirect = props.redirect;
  var isComingSoon$1 = isComingSoon !== undefined ? isComingSoon : false;
  var buttonText$1 = buttonText !== undefined ? buttonText : "Add Details";
  var isApiCall$1 = isApiCall !== undefined ? isApiCall : true;
  var showPopUp = PopUpState.useShowPopUp(undefined);
  var showToast = ToastState.useShowToast(undefined);
  var updateDetails = APIUtils.useUpdateMethod(undefined, undefined);
  var userPermissionJson = Recoil.useRecoilValue(
    HyperswitchAtom.userPermissionAtom,
  );
  var deleteSampleData = async function (param) {
    try {
      var generateSampleDataUrl = APIUtils.getURL(
        /* GENERATE_SAMPLE_DATA */ 21,
        /* Delete */ 4,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
      await Curry._7(
        updateDetails,
        generateSampleDataUrl,
        {},
        /* Delete */ 4,
        undefined,
        undefined,
        undefined,
        undefined,
      );
      return Curry._8(
        showToast,
        "Sample data deleted successfully",
        /* ToastSuccess */ 3,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    } catch (exn) {
      return;
    }
  };
  var onClickHandler = function (param) {
    if (isApiCall$1) {
      if (cardName === "DELETE_SAMPLE_DATA") {
        return Curry._1(showPopUp, {
          heading: "Are you sure?",
          description:
            "This action cannot be undone. This will permanently delete all the sample payments and refunds data. To confirm, click the 'Delete All' button below.",
          popUpType: [/* Warning */ 4, /* WithIcon */ 0],
          handleCancel: {
            text: "Cancel",
            onClick: function (param) {},
          },
          handleConfirm: {
            text: "Delete All",
            onClick: function (param) {
              deleteSampleData(undefined);
            },
          },
        });
      } else {
        return;
      }
    } else if (redirectUrl !== undefined) {
      return RescriptReactRouter.push(
        HSwitchGlobalVars.appendDashboardPath("/" + redirectUrl + ""),
      );
    } else if (redirect !== undefined) {
      return RescriptReactRouter.push(
        HSwitchGlobalVars.appendDashboardPath(
          "/settings?type=" + redirect + "",
        ),
      );
    } else {
      return RescriptReactRouter.push(
        HSwitchGlobalVars.appendDashboardPath("/settings"),
      );
    }
  };
  var accessBasedOnCardName =
    cardName === "DELETE_SAMPLE_DATA"
      ? userPermissionJson.operationsManage
      : /* Access */ 1;
  return React.createElement(
    "div",
    {
      className:
        "flex flex-col bg-white pt-6 pl-6 pr-8 pb-8 justify-between gap-10 border border-jp-gray-border_gray rounded ",
    },
    React.createElement(
      "div",
      undefined,
      React.createElement(
        "div",
        {
          className: "flex justify-between",
        },
        React.createElement(
          "p",
          {
            className: "text-fs-16 font-semibold m-2",
          },
          props.heading,
        ),
        isComingSoon$1
          ? React.createElement(Icon.make, {
              name: "comingSoon",
              size: 25,
              className: "w-36",
            })
          : null,
      ),
      React.createElement(
        "p",
        {
          className: "text-fs-14 font-medium m-2 text-black opacity-50",
        },
        props.subHeading,
      ),
    ),
    React.createElement(ACLButton.make, {
      text: buttonText$1,
      buttonState: isComingSoon$1 ? /* Disabled */ 2 : /* Normal */ 0,
      buttonType: /* Secondary */ 1,
      buttonSize: /* Small */ 2,
      onClick: onClickHandler,
      customButtonStyle: "w-2/3",
      access: accessBasedOnCardName,
    }),
  );
}

var TileComponent = {
  make: HSwitchSettings$TileComponent,
};

function HSwitchSettings$PersonalSettings(props) {
  var featureFlagDetails = Recoil.useRecoilValue(
    HyperswitchAtom.featureFlagAtom,
  );
  var personalSettings = featureFlagDetails.sampleData
    ? [deleteSampleData]
    : [];
  return React.createElement(
    "div",
    {
      className:
        "grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4 md:gap-8",
    },
    personalSettings.map(function (sections, index) {
      return JsxPPXReactSupport.createElementWithKey(
        index.toString(),
        HSwitchSettings$TileComponent,
        {
          heading: sections.heading,
          subHeading: sections.subHeading,
          redirect: Core__Option.getOr(sections.redirect, ""),
          isComingSoon: Core__Option.getOr(sections.isComingSoon, false),
          buttonText: Core__Option.getOr(sections.buttonText, "Add Details"),
          redirectUrl: sections.redirectUrl,
          isApiCall: Core__Option.getOr(sections.isApiCall, false),
          cardName: sections.cardName,
        },
      );
    }),
  );
}

var PersonalSettings = {
  make: HSwitchSettings$PersonalSettings,
};

function HSwitchSettings(props) {
  return React.createElement(
    React.Fragment,
    undefined,
    React.createElement(PageUtils.PageHeading.make, {
      title: "Account Settings",
      subTitle: "Manage payment account configuration and dashboard settings",
    }),
    React.createElement(HSwitchSettings$PersonalSettings, {}),
  );
}

var make = HSwitchSettings;

export { deleteSampleData, TileComponent, PersonalSettings, make };
/* Icon Not a pure module */
