// Generated by ReScript, PLEASE EDIT WITH CARE

import * as InputFields from "../../components/InputFields.bs.js";

var primaryDetails_inputFields = [
  {
    placeholder: "Enter Contact Name",
    label: "Contact Name",
    name: "primary_contact_person",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Contact Phone",
    label: "Contact Phone",
    name: "primary_phone",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Contact Mail",
    label: "Contact Mail",
    name: "primary_email",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
];

var primaryDetails = {
  name: "Primary Details",
  description: "Add primary contact details",
  inputFields: primaryDetails_inputFields,
};

var secondaryDetails_inputFields = [
  {
    placeholder: "Enter Contact Name",
    label: "Contact Name",
    name: "secondary_contact_person",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Contact Phone",
    label: "Contact Phone",
    name: "secondary_phone",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Contact Mail",
    label: "Contact Mail",
    name: "secondary_email",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
];

var secondaryDetails = {
  name: "Secondary Details",
  description: "Add secondary contact details",
  inputFields: secondaryDetails_inputFields,
};

var businessDetails_inputFields = [
  {
    placeholder: "Enter Website Name",
    label: "Website",
    name: "website",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Description",
    label: "Description",
    name: "about_business",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Address Line 1",
    label: "Address Line 1",
    name: "line1",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Address Line 2 ",
    label: "Address Line 2",
    name: "line2",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter Zip Code",
    label: "Zip",
    name: "zip",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
  {
    placeholder: "Enter City",
    label: "City",
    name: "city",
    inputType: function (param) {
      return function (param$1) {
        var param$2;
        var param$3;
        var param$4;
        var param$5;
        var param$6;
        var param$7;
        var param$8;
        var param$9;
        var param$10;
        var param$11;
        var param$12;
        var param$13;
        var param$14;
        var param$15;
        var param$16;
        var param$17;
        var param$18;
        var param$19;
        var param$20;
        var param$21;
        var param$22;
        var param$23;
        var param$24;
        var param$25;
        var param$26;
        var param$27;
        return InputFields.textInput(
          param,
          param$1,
          param$2,
          param$3,
          param$4,
          param$5,
          param$6,
          param$7,
          param$8,
          param$9,
          param$10,
          param$11,
          param$12,
          param$13,
          param$14,
          param$15,
          param$16,
          param$17,
          param$18,
          param$19,
          param$20,
          param$21,
          param$22,
          param$23,
          param$24,
          param$25,
          param$26,
          param$27,
        );
      };
    },
  },
];

var businessDetails = {
  name: "Business Details",
  description: "Add business details",
  inputFields: businessDetails_inputFields,
};

export { primaryDetails, secondaryDetails, businessDetails };
/* InputFields Not a pure module */
