// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Table from "../../components/Table.bs.js";
import * as EntityType from "../../entities/EntityType.bs.js";
import * as LogicUtils from "../../utils/LogicUtils.bs.js";
import * as HSwitchGlobalVars from "../../utils/HSwitchGlobalVars.bs.js";

var defaultColumns = [
  /* CustomerId */ 0, /* Name */ 1, /* Email */ 2, /* PhoneCountryCode */ 4,
  /* Phone */ 3, /* Description */ 5, /* Address */ 6, /* CreatedAt */ 7,
];

var allColumns = [
  /* CustomerId */ 0, /* Name */ 1, /* Email */ 2, /* Phone */ 3,
  /* PhoneCountryCode */ 4, /* Description */ 5, /* Address */ 6,
  /* CreatedAt */ 7,
];

function getHeading(colType) {
  switch (colType) {
    case /* CustomerId */ 0:
      return Table.makeHeaderInfo(
        "customer_id",
        "Customer Id",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* Name */ 1:
      return Table.makeHeaderInfo(
        "name",
        "Customer Name",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* Email */ 2:
      return Table.makeHeaderInfo(
        "email",
        "Email",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* Phone */ 3:
      return Table.makeHeaderInfo(
        "phone",
        "Phone",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* PhoneCountryCode */ 4:
      return Table.makeHeaderInfo(
        "phone_country_code",
        "Phone Country Code",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* Description */ 5:
      return Table.makeHeaderInfo(
        "description",
        "Description",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* Address */ 6:
      return Table.makeHeaderInfo(
        "address",
        "Address",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
    case /* CreatedAt */ 7:
      return Table.makeHeaderInfo(
        "created_at",
        "Created",
        undefined,
        true,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
        undefined,
      );
  }
}

function getCell(customersData, colType) {
  switch (colType) {
    case /* CustomerId */ 0:
      return {
        TAG: /* Text */ 1,
        _0: customersData.customer_id,
      };
    case /* Name */ 1:
      return {
        TAG: /* Text */ 1,
        _0: customersData.name,
      };
    case /* Email */ 2:
      return {
        TAG: /* Text */ 1,
        _0: customersData.email,
      };
    case /* Phone */ 3:
      return {
        TAG: /* Text */ 1,
        _0: customersData.phone,
      };
    case /* PhoneCountryCode */ 4:
      return {
        TAG: /* Text */ 1,
        _0: customersData.phone_country_code,
      };
    case /* Description */ 5:
      return {
        TAG: /* Text */ 1,
        _0: customersData.description,
      };
    case /* Address */ 6:
      return {
        TAG: /* Date */ 4,
        _0: customersData.address,
      };
    case /* CreatedAt */ 7:
      return {
        TAG: /* Date */ 4,
        _0: customersData.created_at,
      };
  }
}

function itemToObjMapper(dict) {
  return {
    customer_id: LogicUtils.getString(dict, "customer_id", ""),
    name: LogicUtils.getString(dict, "name", ""),
    email: LogicUtils.getString(dict, "email", ""),
    phone: LogicUtils.getString(dict, "phone", ""),
    phone_country_code: LogicUtils.getString(dict, "phone_country_code", ""),
    description: LogicUtils.getString(dict, "description", ""),
    address: LogicUtils.getString(dict, "address", ""),
    created_at: LogicUtils.getString(dict, "created_at", ""),
    metadata: LogicUtils.getJsonObjectFromDict(dict, "metadata"),
  };
}

function getCustomers(json) {
  return LogicUtils.getArrayDataFromJson(json, itemToObjMapper);
}

var customersEntity = EntityType.makeEntity(
  "",
  getCustomers,
  defaultColumns,
  allColumns,
  getHeading,
  getCell,
  "",
  undefined,
  undefined,
  undefined,
  undefined,
  function (customerData) {
    return HSwitchGlobalVars.appendDashboardPath(
      "/customers/" + customerData.customer_id + "",
    );
  },
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
  undefined,
);

export {
  defaultColumns,
  allColumns,
  getHeading,
  getCell,
  itemToObjMapper,
  getCustomers,
  customersEntity,
};
/* customersEntity Not a pure module */
