// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function useLottieIcon(isSelected, selectedLottieJson, deselectLottieJson) {
  var hasRendered = React.useRef(false);
  var match = React.useState(function () {
    if (isSelected) {
      return deselectLottieJson;
    } else {
      return selectedLottieJson;
    }
  });
  var setDefaultState = match[1];
  var match$1 = React.useState(function () {
    return false;
  });
  var setAutoplay = match$1[1];
  React.useEffect(
    function () {
      if (hasRendered.current) {
        Curry._1(setAutoplay, function (param) {
          return true;
        });
        var newVal = isSelected ? selectedLottieJson : deselectLottieJson;
        Curry._1(setDefaultState, function (param) {
          return newVal;
        });
      } else if (selectedLottieJson !== null && deselectLottieJson !== null) {
        Curry._1(setDefaultState, function (param) {
          if (isSelected) {
            return deselectLottieJson;
          } else {
            return selectedLottieJson;
          }
        });
        hasRendered.current = true;
      }
    },
    [isSelected, selectedLottieJson, deselectLottieJson],
  );
  return [match[0], match$1[0]];
}

export { useLottieIcon };
/* react Not a pure module */
