// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function defaultSetter(param) {}

var authStatusContext = React.createContext([/* LoggedOut */ 0, defaultSetter]);

var make = authStatusContext.Provider;

export { defaultSetter, authStatusContext, make };
/* authStatusContext Not a pure module */
