// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Loader from "../components/Loader.bs.js";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as ErrorBoundary from "../components/ErrorBoundary.bs.js";

function ReactSuspenseWrapper(props) {
  var loadingText = props.loadingText;
  var loadingText$1 = loadingText !== undefined ? loadingText : "Loading...";
  return React.createElement(React.Suspense, {
    children: Caml_option.some(
      React.createElement(ErrorBoundary.make, {
        children: props.children,
      }),
    ),
    fallback: Caml_option.some(
      React.createElement(Loader.make, {
        loadingText: loadingText$1,
      }),
    ),
  });
}

var make = ReactSuspenseWrapper;

export { make };
/* react Not a pure module */
