// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Icon from "../../components/Icon.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Caml_option from "rescript/lib/es6/caml_option.js";
import * as InputFields from "../../components/InputFields.bs.js";
import * as ReactFinalForm from "../../libraries/ReactFinalForm.bs.js";
import * as ReactFinalForm$1 from "react-final-form";
import * as AddDataAttributes from "../../components/AddDataAttributes.bs.js";

function TableSearchFilter(props) {
  var customInputBoxWidth = props.customInputBoxWidth;
  var customSearchBarWrapperWidth = props.customSearchBarWrapperWidth;
  var setSearchVal = props.setSearchVal;
  var searchVal = props.searchVal;
  var placeholder = props.placeholder;
  var filterLogic = props.filterLogic;
  var data = props.data;
  var filterLogic$1 =
    filterLogic !== undefined ? filterLogic : function (param) {};
  var customSearchBarWrapperWidth$1 =
    customSearchBarWrapperWidth !== undefined
      ? customSearchBarWrapperWidth
      : "w-1/4";
  var customInputBoxWidth$1 =
    customInputBoxWidth !== undefined ? customInputBoxWidth : "w-72";
  var filterData = React.useCallback(Curry.__1(filterLogic$1), []);
  React.useEffect(
    function () {
      Curry._1(filterData, [searchVal, data]);
    },
    [searchVal],
  );
  var onChange = function (ev) {
    var value = ev.target.value;
    Curry._1(setSearchVal, function (param) {
      return value;
    });
  };
  var handleSubmit = function (param, param$1) {
    return Promise.resolve(null);
  };
  var inputSearch_onBlur = function (_ev) {};
  var inputSearch_onFocus = function (_ev) {};
  var inputSearch = {
    name: "search",
    onBlur: inputSearch_onBlur,
    onChange: onChange,
    onFocus: inputSearch_onFocus,
    value: searchVal,
    checked: true,
  };
  return React.createElement(AddDataAttributes.make, {
    attributes: [["data-testid", "table-search-filter"]],
    children: React.createElement(
      "div",
      {
        className: customSearchBarWrapperWidth$1,
      },
      React.createElement(ReactFinalForm$1.Form, {
        initialValues: "",
        onSubmit: handleSubmit,
        render: function (_handleSubmit) {
          return InputFields.textInput(
            inputSearch,
            placeholder,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            Caml_option.some(
              React.createElement(Icon.make, {
                name: "search",
                size: 16,
              }),
            ),
            undefined,
            undefined,
            undefined,
            "!h-10 " + customInputBoxWidth$1 + "",
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
            undefined,
          );
        },
        subscription: ReactFinalForm.subscribeToValues,
      }),
    ),
  });
}

var make = TableSearchFilter;

export { make };
/* Icon Not a pure module */
